spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacoCloud
  h2:
    console:
      enabled: true
  security:
    user:
      name: buzz
      password: infinity
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook client id>
            client-secret: <facebook client secret>
            scope:
              - email
              - public_profile
server:
  port: 8090

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN

